---
# handlers file for lamp
- name: restart apache server
  service:
    name: apache2
    state: restarted
- name: restart apache server on fedora
  service:
    name: httpd
    state: restarted
- name: sample php file
  copy:
      dest: "{{php_file}}"
      content: |
            <?php
            echo"hello world"
            ?>
- name: set database password for the first time
  mysql_user:
    name: root
    password: "{{db_root_pass}}"
    login_unix_socket: /var/lib/mysql/mysql.sock # we use this because the root doesn't use TCP, only socket file.
    check_implicit_admin: true # we use this parameter if we dont know the sql password
    state: present
