---
- block:
    - name: install apache service
      yum:
        name: httpd
        state: present
    - name: start apache service
      service:
        name: httpd
        state: started
  when: ansible_facts['distribution'] == 'Fedora'
  become_user: "{{user}}"
  rescue:
    - name: test the error handling
      debug:
       msg: "I've got an error"
- block:
    - name: install mysql service 
      yum:
        name: mariadb-server
        state: present
    - name: start mysql service
      service:
        name: mariadb
        state: started
  when: ansible_facts['distribution'] == 'Fedora'
  become_user: "{{user}}"
  always:
    - name: test the error handling
      debug:
       msg: "just for testing"
- block:
    - name: install php service 
      yum:
        name: php
        state: present
  when: ansible_facts['distribution'] == 'Fedora'
  become_user: "{{user}}"
  notify: 
    - restart apache server on fedora
    - sample php file
- block:
    - name: allow ports on firwall
      firewalld:
         port: "{{ item }}/tcp"
         permanent: true
         state: enabled
      loop:
        - 80
        - 443
      ignore_errors: true
  when: ansible_facts['distribution'] == 'Fedora'
  become_user: "{{user}}"
