---
- block:
    - name: install apache service
      yum:
        name: httpd
        state: present
    - name: start apache service
      service:
        name: httpd
        state: started
  when: ansible_facts['distribution'] == 'Fedora'
  become_user: "{{user}}"
  always: 
    debug:
      msg: "for now it's just for test"

- block:
    - name: install mysql service 
      yum:
        name: mysql-server
        state: present
    - name: start mysql service
      service:
        name: mysqld
        state: started
  when: ansible_facts['distribution'] == 'Fedora'
  become_user: "{{user}}"
  secure: 
    debug:
      msg: "there is a problem installing mysql and start it"

- block:
    - name: install php service 
      yum:
        name: php
        state: present
    - name: start php service
      service:
        name: php-fpm
        state: started
  when: ansible_facts['distribution'] == 'Fedora'
  become_user: "{{user}}"
  notify: restart apache server on fedora

    