---
- block:
    - name: install apache service
      apt:
        name: apache2
        state: present
    - name: start apache service
      service:
        name: apache2
        state: started
  always:
    - name: test the error handling
      debug:
       msg: "just for testing"
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"

- block:
    - name: install mysql service 
      apt:
        name: mysql-server
        state: present
    - name: start mysql service
      service:
        name: mysql
        state: started
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"
  rescue:
    - name: test the error handling
      debug:
       msg: "I've got an error"

- block:
    - name: install php service 
      apt:
        name:
          - php
          - php-mysql
        state: present
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"
  notify:
    -  restart apache server
    -  sample php file
- block:

      - name: allow  ports on ufw
        ufw:
          rule: allow
          port: "{{item}}"

        loop:
          - 80
          - 443
        ignore_errors: yes
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"
