---
- block:
    - name: install apache service
      apt:
        name: apache2
        state: present
    - name: start apache service
      service:
        name: apache2
        state: started
  always:
    - name: test the error handling
      debug:
       msg: "just for testing"
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"

- block:
    - name: install mysql service 
      apt:
        name: mysql-server
        state: present
    - name: start mysql service
      service:
        name: mysql
        state: started
    - name: install python3-pip if not installed #it's mandatory to change the sql password
      apt:
        name: python3-pip
        state: present
    - name: making sure PyMySQL installed #it's also mandatory because it's a dependency of python3-pip
      pip:
        name: PyMySQL
        state: present
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"
  notify: set database password for the first time
  rescue:
    - name: test the error handling
      debug:
       msg: "I've got an error"
# - block:                # (use this block if you wanna change the password)
#   - name: sign in to the my sql    
#     mysql_user:
#       login_user: root
#       login_password: root
#       login: new_user
#       password: new_password
#       state: present 
- block:
    - name: install php service 
      apt:
        name:
          - php
          - php-mysql
        state: present
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"
  notify:
    -  restart apache server
    -  sample php file
- block:

      - name: allow  ports on ufw
        ufw:
          rule: allow
          port: "{{item}}"

        loop:
          - 80
          - 443
        ignore_errors: true
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"
