---
- block:
    - name: install apache service
      apt:
        name: apache2
        state: present
    - name: start apache service
      service:
        name: apache2
        state: started
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"

- block:
    - name: install mysql service 
      apt:
        name: mysql-server
        state: present
    - name: start mysql service
      service:
        name: mysql
        state: started
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"

- block:
    - name: install php service 
      apt:
        name: php
        state: present
    - name: start php service
      service:
        name: php8.1-fpm
        state: started
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"