---
- block:
    - name: install apache service
      apt:
        name: apache2
        state: present
    - name: start apache service
      service:
        name: apache2
        state: started
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"
  always: 
    debug:
      msg: "for now it's just for test"

- block:
    - name: install mysql service 
      apt:
        name: mysql-server
        state: present
    - name: start mysql service
      service:
        name: mysql
        state: started
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"
  secure: 
    debug:
      msg: "there is a problem installing mysql and start it"

- block:
    - name: install php service 
      apt:
        name: php
        state: present
    - name: start php service
      service:
        name: php8.1-fpm
        state: started
  when: ansible_facts['distribution'] == 'Ubuntu'
  become_user: "{{user}}"
  notify: restart apache server